[package]
name = "engine"
version = "0.0.0"
authors = ["Clomance"]
edition = "2018"

[dependencies]
image = "0.23.4"
glium = "0.27.0"
rusttype = "0.9.1"

[dependencies.sdl2]
version = "0.34.0"
default-features = false
features = ["mixer"]