# Attention!
# Repository name must be equal to [package] name
# Otherwise step "Package as archive" will not work
#
# Compile errors:
# 1. 32 bit: error on X86_32
# 2. IOS: cannot find value `kAudioDevicePropertyBufferFrameSize` in crate `sys`
# 3. Linux arch, aarch64: Unable to locate package alsa-lib-devel.aarch64
# 4. Windows aarch64: minimp3/minimp3.h(187): fatal error C1189: #error:  MINIMP3_ONLY_SIMD used, but SSE/NEON not enabled

name: Cross_v3

on:
  release:
    types: [created]

env:
  CRATE_NAME: runiq_ahash
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1


jobs:
  x86_64_release:
    permissions: write-all
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          
          - os_name: Linux-x86_64-gnu
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: ${{ github.event.repository.name }}
            name: ${{ github.event.repository.name }}-x86_64-unknown-linux-gnu.tar.gz
            
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: ${{ github.event.repository.name }}.exe
            name: ${{ github.event.repository.name }}-x86_64-pc-windows-msvc.zip
          
          - os_name: Windows-x86_64-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: ${{ github.event.repository.name }}.exe
            name: ${{ github.event.repository.name }}-x86_64-pc-windows-gnu.zip

          - os_name: macOS-aarch64
            os: macos-12
            target: aarch64-apple-darwin
            bin: ${{ github.event.repository.name }}
            name: ${{ github.event.repository.name }}-macOS-aarch64-apple-darwin.tar.gz
            skip_tests: true
          
          - os_name: macOS-x86_64
            os: macos-12
            target: x86_64-apple-darwin
            bin: ${{ github.event.repository.name }}
            name: ${{ github.event.repository.name }}-macOS-x86_64-apple-darwin.tar.gz
            
        toolchain:
          - stable

    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2

      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.name, 'musl')
        
      - name: Install libasound2-dev on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes g++ pkg-config libx11-dev libasound2-dev libudev-dev
        if: contains(matrix.platform.name, 'linux')

      - name: Install libunwind8-dev for Android
        run: sudo apt-get update --yes && sudo apt-get install --yes android-libunwind-dev
        if: contains(matrix.platform.target, 'aarch64-linux-android')

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--release"
          strip: true
        if: |
          matrix.toolchain == 'stable' &&
          contains(matrix.platform.target, 'aarch64-linux-android') == false &&
          ( startsWith( github.ref, 'refs/tags/v' ) ||
            github.ref == 'refs/tags/test-release' )
            
      - name: Build binary for aarch64-linux-android
        shell: bash
        run: |
          rustup target add aarch64-linux-android
          # Adapted from https://github.com/briansmith/ring/blob/main/mk/cargo.sh
          set -eux -o pipefail
          OS_NAME=$(uname -s | tr A-Z a-z)

          # Avoid putting the Android tools in `$PATH` because there are tools in this
          # directory like `clang` that would conflict with the same-named tools that may
          # be needed to compile the build script, or to compile for other targets.
          if [ -n "${ANDROID_HOME-}" ]; then
            # Keep the next line in sync with the corresponding line in install-build-tools.sh.
            ndk_version=25.2.9519653
            ANDROID_NDK_ROOT=${ANDROID_NDK_ROOT:-${ANDROID_HOME}/ndk/$ndk_version}
          fi
          if [ -n "${ANDROID_NDK_ROOT-}" ]; then
            android_tools=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/${OS_NAME}-x86_64/bin
          fi
          
          export CC_aarch64_linux_android=$android_tools/aarch64-linux-android21-clang
          export AR_aarch64_linux_android=$android_tools/llvm-ar
          export CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$android_tools/aarch64-linux-android21-clang

          cargo build --verbose --release --target=aarch64-linux-android
        if: |
          matrix.toolchain == 'stable' &&
          contains(matrix.platform.target, 'aarch64-linux-android') &&
          ( startsWith( github.ref, 'refs/tags/v' ) ||
            github.ref == 'refs/tags/test-release' )

      - name: Package as archive
        shell: bash
        run: |
          echo running archive
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ github.event.repository.name }}.exe
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ github.event.repository.name }}
          fi
          cd -
        if: |
          matrix.toolchain == 'stable' &&
          ( startsWith( github.ref, 'refs/tags/v' ) ||
            github.ref == 'refs/tags/test-release' )

      - name: Publish release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.platform.os_name }}
          path: "${{ github.event.repository.name }}-*"
        if: matrix.toolchain == 'stable'

      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.platform.name }}
        if: |
          matrix.toolchain == 'stable' &&
            ( startsWith( github.ref, 'refs/tags/v' ) ||
            github.ref == 'refs/tags/test-release' )

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: "${{ github.event.repository.name }}-*"
          body_path: Changes.md
        if: matrix.toolchain == 'stable' && startsWith( github.ref, 'refs/tags/v' )
